Create vespa.json
swirlai/swirl-search pull request #718
Opened 2023-10-10 19:33 UTC by HarshMN2345

Implemented Vespa Search
Associated issue #692

To utilize this functionality, follow these steps:

Start Vespa Instance:
Ensure you have a running Vespa instance. If not, refer to Vespa's official documentation for installation instructions.

Add JSON File to Swirl Configuration:
Insert the provided JSON file into your Swirl configuration file.

Restart Swirl:
Restart Swirl to apply the changes.

Now, you can start searching for Vespa content. Use the following command:

swirl search vespa "my query"

2023-10-10 19:34 UTC, HarshMN2345 commented
@sidprobstein please review it

2023-10-10 19:56 UTC, HarshMN2345 commented
@dnicodemus pls review it

2023-10-20 18:16 UTC, sid-swirl commented
This looks awesome @HarshMN2345 ... I believe you should remove the space from the result_mappings. Can you add author, date_published and url also?

Also, does Vespa return the  # found, # retrieved? If possible, add those to the response_mappings as noted here: https://docs.swirl.today/2.-User-Guide.html#response-mappings

If you can post a vespa JSON response, we can help with these! Thank you again!

2023-10-20 18:25 UTC, HarshMN2345 commented
@sid-swirl  i have done the changes as asked

2023-10-26 16:40 UTC, sidprobstein commented on SearchProviders/vespa.json
> +  "response_mappings": "RESULTS=root_object.hits.hits, #found=root_object.hits.found, #retrieved=root_object.hits.retrieved",
Hi @HarshMN2345 ... this is good, however, #found and #retrieved are not legal. They should be FOUND and RETRIEVED

2023-10-26 16:41 UTC, sidprobstein requested changes
Please address commented change thank you

2023-10-26 16:43 UTC, sidprobstein requested changes
Also, please re-target this to swirlai:develop branch as per the guidelines. Thank you.

https://swirl.today/contribute-to-swirl-this-hacktoberfest-2023/

2023-10-26 17:03 UTC, HarshMN2345 commented
@sid-swirl okay i am making a new pr for the changes and closing this one

2023-10-26 17:03 UTC, closed without merging